# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ssmsh < Formula
  desc "A shell for the EC2 Parameter Store"
  homepage "https://github.com/bwhaley/ssmsh"
  version "1.4.9"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/bwhaley/ssmsh/releases/download/v1.4.9/ssmsh_1.4.9_darwin_arm64.tar.gz"
      sha256 "a82cbebe3991fddefdea953b3e2162a95583a7b329ab30b87920b766ccd4fd5a"

      def install
        bin.install "ssmsh"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/bwhaley/ssmsh/releases/download/v1.4.9/ssmsh_1.4.9_darwin_amd64.tar.gz"
      sha256 "45d5a592b2aba830f49296f2339d388469a9478873aba805581b84f4a2e98fd7"

      def install
        bin.install "ssmsh"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/bwhaley/ssmsh/releases/download/v1.4.9/ssmsh_1.4.9_linux_arm64.tar.gz"
      sha256 "ebb1590b9be0cf5f5f90bea8fdfb5f462989ba4947586aed38c889aea9e896a0"

      def install
        bin.install "ssmsh"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/bwhaley/ssmsh/releases/download/v1.4.9/ssmsh_1.4.9_linux_amd64.tar.gz"
      sha256 "880ce1fd987ce31e68ae582ab83c24f71e9b69319b6176a131bb73e3fe48abdf"

      def install
        bin.install "ssmsh"
      end
    end
  end
end
