# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ssmsh < Formula
  desc "A shell for the EC2 Parameter Store"
  homepage "https://github.com/bwhaley/ssmsh"
  version "1.4.7"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/bwhaley/ssmsh/releases/download/v1.4.7/ssmsh_1.4.7_darwin_amd64.tar.gz"
      sha256 "f5428d7a0abc0ddb18cb4330b8da1e859aeac7c9284041403f5f31bc39ffb0e0"

      def install
        bin.install "ssmsh"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/bwhaley/ssmsh/releases/download/v1.4.7/ssmsh_1.4.7_linux_amd64.tar.gz"
      sha256 "2dd8d5f28ae6b938daca02dcf0faac028575f4c938d51e8cf0ae5186c5072f48"

      def install
        bin.install "ssmsh"
      end
    end
  end
end
