# Generated by scripts/update_homebrew.py. Do not edit release metadata by hand.
class Ssmsh < Formula
  desc "Interactive shell for AWS Systems Manager Parameter Store"
  homepage "https://github.com/bwhaley/ssmsh"
  url "https://github.com/bwhaley/ssmsh/releases/download/v2.1.0/ssmsh_2.1.0_source.tar.gz"
  sha256 "b47b443ba5ffbc12798259854488901254b2facacd58f8110e069b80ebad6497"
  license "MIT"

  depends_on "go" => :build

  def install
    system "go", "build", *std_go_args(ldflags: "-s -w -X main.Version=#{version}"), "."
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/ssmsh -version")
  end
end
