#!/usr/bin/env python3
"""Generate the source-build formula from a GoReleaser checksum manifest."""
import pathlib
import re
import sys

version, manifest, destination = sys.argv[1:]
if not re.fullmatch(r"\d+\.\d+\.\d+", version):
    raise SystemExit("Homebrew updates require a stable x.y.z version")
archive = f"ssmsh_{version}_source.tar.gz"
checksums = dict(line.split(maxsplit=1)[::-1] for line in pathlib.Path(manifest).read_text().splitlines())
checksum = checksums[archive]
if not re.fullmatch(r"[0-9a-f]{64}", checksum):
    raise SystemExit("Invalid source archive checksum")
pathlib.Path(destination).write_text(f'''# Generated by scripts/update_homebrew.py. Do not edit release metadata by hand.
class Ssmsh < Formula
  desc "Interactive shell for AWS Systems Manager Parameter Store"
  homepage "https://github.com/bwhaley/ssmsh"
  url "https://github.com/bwhaley/ssmsh/releases/download/v{version}/{archive}"
  sha256 "{checksum}"
  license "MIT"

  depends_on "go" => :build

  def install
    system "go", "build", *std_go_args(ldflags: "-s -w -X main.Version=#{{version}}"), "."
  end

  test do
    assert_match version.to_s, shell_output("#{{bin}}/ssmsh -version")
  end
end
''')
