name: Build

on:
  push:

env:
  AWS_DEFAULT_REGION: us-east-1

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.56.1
          args: --enable golint
  test-and-build:
    name: Test and build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Vet
        run: go vet -v $(go list ./...)
      - name: Test
        run: go test -v $(go list ./...)
      - name: Build
        run: make build
